config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  root 'categories#index'
  get '/splash', to: 'splash#index', as: 'splash'

  resources :categories do
    resources :expenses, only: [:new, :create]
  end
end

app/views/layouts/shared/_flash_messages.html.erb
<% if notice %>
  <p class="notice"><%= notice %></p>
<% else %>
  <p class="alert"><%= alert %></p>
<% end %>  

app/views/layouts/shared/_header.html.erb
<section class="header bg-primary text-white py-2 d-flex justify-content-between">
  <% if back_button_enabled? %>
    <a href="#" class="text-white" onclick="goBack(); return false;">
      <i class="fa-solid fa-chevron-left text-white" style="font-size: 1.5rem;"></i>
    </a>
  <% else %>
    <!-- Display a placeholder or remove the arrow -->
  <% end %>
  <h1 class="h3"><%= heading %></h1>
    <div class="d-flex justify-content-end mb-1 position-relative">
      <% if user_signed_in? %>
        <%= button_to("Log Out", destroy_user_session_path, method: :delete, class: "btn btn-danger") %>
      <% end %>
    </div>
</section>

<script>
  function goBack() {
    <% if back_to_categories? %>
      window.location.href = '<%= categories_path %>';
    <% else %>
      window.history.back();
    <% end %>
  }
</script>


<%= render partial: "layouts/shared/notice" %>

app/views/layouts/shared/_navbar.html.erb
<% if current_user %>  
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
<% end %>  

app/views/layouts/shared/_notice.html.erb
<% if flash.any? %>
  <% flash.each do |type, msg| %>
    <div class="alert flash-notice flash-<%= type %> mb-4">
      <h3 class="alert-heading <%= type === 'notice' ? 'bg-success' : 'bg-danger' %> text-white p-2">
        <%= msg %>
      </h3>
    </div>
  <% end %>
<% end %>