config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  root 'categories#index'
  get '/splash', to: 'splash#index', as: 'splash'

  resources :categories do
    resources :expenses, only: [:new, :create]
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_expenses, dependent: :destroy
  has_many :expenses, through: :category_expenses
  has_many :expenses, after_add: :update_sum_spent, after_remove: :update_sum_spent
  has_one_attached :icon
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'

  attr_accessor :sum_spent

  validates :name, presence: true
  validates :icon, presence: true

  has_many :expenses, after_add: :update_sum_spent, after_remove: :update_sum_spent

  private

  def update_sum_spent(_expense)
    self.sum_spent = expenses.sum(:amount)
    save
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :verify_user
  before_action :set_user

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = @user.categories.build(category_params)

    if @category.save
      redirect_to categories_path, notice: 'Category added successfully'
    else
      flash.now[:alert] = @category.errors.full_messages.first if @category.errors.any?
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @category = Category.find(params[:id])

    unless @category.user == @user
      redirect_to categories_path, notice: 'You are not authorized to access this page!'
      return
    end

    @expenses = @category.expenses.order(created_at: :desc)
    @total = @expenses.sum(:amount)
  end

  private

  def set_user
    @user = current_user || User.new
  end

  def category_params
    params.require(:category).permit(:name, :icon, :image_url)
  end

  def verify_user
    return if user_signed_in?

    redirect_to splash_path
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div class="shadow p-3 mb-5 bg-white rounded">
  <%= link_to category_path(category) do %>
    <div id="<%= dom_id category %>" class="col">
      <div class="toolbar2">
        <%= link_to(category_path(category)) do %>
          <img style="width:10%" src="<%= asset_url(category.icon) %>" />
        <% end %>
        <div><%= category.name.capitalize %></div>
        <div><%= number_to_currency(Expense.all.where(category_id: category.id).sum(:amount)) %></div>
        <%= link_to image_tag("https://img.icons8.com/ios/344/right--v1.png"), category, class: "back_btn" %>
      </div>
      <div class="date"> <%= category.created_at.strftime("%e %b %Y") %> </div>
    </div>
  <% end %>
</div>

app/views/categories/_form.html.erb
<div class="category-new shadow p-3 mb-5 bg-white rounded">
  <%= form_with(model: category, class: "needs-validation", novalidate: true) do |form| %>
    <% if category.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <h2><%= pluralize(category.errors.count, "error") %> prevented this category from being saved:</h2>
        <ul>
          <% category.errors.full_messages.each do |error| %>
            <li><%= error %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="mb-3">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control", required: true %>
    </div>
    <div class="mb-3">
      <%= form.label :icon, class: "form-label"  %>
      <%= form.select :icon, {"🛒" => "https://cdn-icons-png.flaticon.com/512/891/891462.png", "🎮" =>"https://cdn-icons-png.flaticon.com/512/808/808439.png", "🚌" => "https://cdn-icons-png.flaticon.com/512/1034/1034795.png","💄"=>"https://img.icons8.com/external-wanicon-flat-wanicon/344/external-make-up-beauty-cosmetics-wanicon-flat-wanicon.png"},
       {}, class: "form-control", required: true %>
    </div>
    <div class="mb-3">
      <%= form.submit "Create Category", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/categories/edit.html.erb
<div class="container my-5">
  <h1 class="mb-4">Edit Category</h1>

  <%= render "form", category: @category %>

  <div class="mt-4">
    <%= link_to "Show Category", @category, class: "btn btn-secondary me-2" %> |
    <%= link_to "Back to Categories", categories_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/categories/index.html.erb
<%= render partial: 'layouts/shared/header', locals: { heading: 'CATEGORIES', path: categories_path } %>

<div class="d-flex flex-column justify-content-between">
  <div>
    <% @categories.each do |category| %>
      <ul class="list-unstyled">
        <li class="card mb-3">
          <%= link_to category_path(category), class: "flex-row text-decoration-none text-dark" do %>
            <div class=" w-100">
              <div class="d-flex justify-content-between mt-2">
                <h3><%= category.name %></h3>
                <h3>$<%= category.expenses.sum(:amount) %></h3>
              </div>
              <p><%= category.created_at.strftime("%d-%m-%Y") %></p>
            </div>
          <% end %>
        </li>
      </ul>
    <% end %>
  </div>
  <div class="w-100 d-flex border p-2 bg-success flex-column justify-content-center align-items-center position-absolute bottom-0 align-self-center">
    <div class="btn-action border rounded">
    <%= link_to new_category_path, class: "btn btn-success" do %>
      Add new category
    <% end %>
  </div>
  </div>
</div>

app/views/categories/new.html.erb
<%= render partial: 'layouts/shared/header', locals: { heading: 'ADD NEW CATEGORY', path: new_category_path } %>

<%= form_with model: @category, url: categories_path, local: true, class: 'form' do |f| %>
  <div class="mb-3">
    <%= f.label :name, class: "form-label" %>
    <%= f.text_field :name, autofocus: true, autocomplete: "off", placeholder: "Category Name", class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :icon, class: "form-label" %>
    <%= f.file_field :icon, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/categories/show.html.erb
<%= render partial: 'layouts/shared/header', locals: { heading: 'TRANSACTIONS', path: category_path(@category) } %>

<div class="card mb-3 w-100">
  <div class="py-4 d-flex justify-content-between">
    <h3 class="card-title"><%= @category.name %></h3>
    <h3 class="card-text">$<%= @expenses.sum(:amount) %></h3>
  </div>
</div>

<div class="expense d-flex flex-column">
  <% @expenses.each do |expense| %>
    <ul class="list-unstyled mb-3">
      <li class="card mb-3">
        <div class="d-flex align-items-center">
          <div class="ml-1">
            <% if @category.icon.attached? %>
              <%= image_tag(@category.icon, class: 'img-fluid rounded-circle', style: 'width: 50px; height: 50px;') %>
            <% else %>
              <%= image_tag('group.png', class: 'img-fluid rounded-circle', style: 'width: 50px; height: 50px;') %>
            <% end %>
          </div>
          <div class="w-100 px-2 mt-3">
            <div class="d-flex justify-content-between">
              <h3><%= expense.name %></h3>
              <h3>$<%= expense.amount %></h3>
            </div>
            <p><%= expense.created_at.strftime("%d-%m-%Y") %></p>
          </div>
        </div>
      </li>
    </ul>
  <% end %>
  <div class="d-flex bg-success w-100 justify-content-center position-absolute bottom-0 align-self-center p-2" role="alert">
    <div class="mb-3 border rounded">
    <%= link_to new_category_expense_path(category_id: @category.id), class: "btn btn-success" do %>
      Add New Expense
    <% end %>
  </div>
  </div>
</div>