config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  root 'categories#index'
  get '/splash', to: 'splash#index', as: 'splash'

  resources :categories do
    resources :expenses, only: [:new, :create]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories, class_name: 'Category', dependent: :destroy, foreign_key: 'user_id'
  has_many :expenses, class_name: 'Expense', dependent: :destroy, foreign_key: 'user_id'
  validates :name, presence: true
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :find_category

  def new
    @expense = @category.expenses.new
  end

  def create
    return redirect_to categories_path, notice: 'You can only create expenses from your categories' unless @category.user == current_user

    @expense = @category.expenses.new(expense_params)
    @expense.user = current_user

    if @expense.save
      flash[:notice] = 'Expense created successfully'
      update_category_sum_spent
      redirect_to @category
    else
      flash[:alert] = @expense.errors.full_messages.first if @expense.errors.any?
      render :new, status: :unprocessable_entity
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount)
  end

  def find_category
    @category = Category.find(params[:category_id])
  end

  def update_category_sum_spent
    # Update the sum spent for the category after creating a new expense
    @category.update(sum_spent: @category.expenses.sum(:amount))
  end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/new.html.erb
<%= render partial: 'layouts/shared/header', locals: { heading: 'ADD NEW EXPENSE', path: categories_path(@category) } %>

<%= form_with model: @expense, url: category_expenses_path, local: true, class: 'form' do |f| %>
  <div class="mb-3">
    <%= f.text_field :name, autofocus: true, autocomplete: "off", placeholder: "Name", class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.number_field :amount, autofocus: false, autocomplete: "off", placeholder: "Amount", class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :category_ids, "Select one or more categories:", class: "form-label" %>
    <div class="checkbox-btn">
      <%= f.collection_check_boxes :category_ids, current_user.categories, :id, :name, class: "form-check-input" do |b| %>
        <div class="form-check">
          <%= b.check_box %>
          <%= b.label class: "form-check-label" %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="mb-3">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>